config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/auth/login', to: 'users#login', as: 'login_user'
  get '/auth/logout', to: 'users#logout', as: 'logout_user'
  get '/profile', to: 'users#show', as: 'profile'
  post '/auth/login', to: 'users#authenticate', as: 'auth_user'
  root "users#index"
  get '/auth/spotify/callback', to: 'users#spotify'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true
  validates :password_confirmation, presence: true
  validates :spotify_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :update_user, only: %i[ index ]
  include BCrypt
  # GET /users or /users.json
  def index
  end

  # GET /users/login
  def login
    @user = User.new
  end
  
  # GET /users/login
  def logout
    @user = nil
    cookies.delete :user_id
    redirect_to root_path
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def spotify
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])

    @user = User.find_by spotify_id: @spotify_user.id

    if @user.nil?
      @user = User.new
      @user.spotify_id = @spotify_user.id
      render new_user_path
    else
      cookies.encrypted[:user_id] = { value: @user.id, expires: Time.now + 3600}
      if params[:callback_address].nil?
        redirect_to profile_path
      else
        redirect_to params[:callback_address]
      end
    end
  end

  def authenticate
    user = user_params
    @user = User.find_by username: user[:username]

    unless @user.nil?
      db_pass = Password.new @user.password_digest
      if db_pass == user[:password]
        cookies.encrypted[:user_id] = { value: @user.id, expires: Time.now + 3600}
        if params[:callback_address].nil?
          redirect_to profile_path
        else
          redirect_to params[:callback_address]
        end
      end
    end
    @user = User.new
    @user.errors.add(:base, 'Invalid credentials')
    render :login
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      update_user
      return unless @user.nil?

      redirect_to login_user_path, status: :unauthorized, callback_address: request.path
    end

    def update_user
      session_user = cookies.encrypted[:user_id]
      @user = session_user ? User.find(session_user) : nil
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user)
            .permit(:username, :password, :password_confirmation, :spotify_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SpotiFynder</title>
  <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
    rel="stylesheet" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'iconify', 'data-turbolinks-track': 'reload' %>
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

</head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>

app/views/users/_bg_circles.html.erb
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <%= yield %>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>

app/views/users/_footer.html.erb
<footer class="py-5 bg-black">
  <div class="container px-5">
    <p class="m-0 text-center text-white small">Copyright &copy; SpotiFynder <%= Time.now.year %></p>
  </div>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_area :username %>
  </div>

  <div class="field">
    <%= form.label :password_hash %>
    <%= form.text_area :password_hash %>
  </div>

  <div class="field">
    <%= form.label :password_salt %>
    <%= form.text_area :password_salt %>
  </div>

  <div class="field">
    <%= form.label :spotify_id %>
    <%= form.text_area :spotify_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <div class="container px-5">
    <a class="navbar-brand" href="#page-top">SpotiFynder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <% if @user.nil? %>
          <li class="nav-item"><%= link_to "Sign Up", '/auth/spotify', :method => :post, :class => "nav-link" %></li>
          <li class="nav-item"><%= link_to "Log In", '/auth/login', :class => "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to @user.username, @user, :class => "nav-link" %></li>
          <li class="nav-item"><%= link_to "Log out", logout_user_path, :class => "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_signin_form.html.erb
<div class="container">
  <%= form_with model: user, url: auth_user_path do |form| %>
  <div class="row justify-content-center">

    <div class="col-md-6 contents">
      <div class="row justify-content-center">
        <% if user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited you from logging in:</h2>
            <ul>
              <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="col-md-12">
          <div class="form-block">
            <div class="mb-4">
              <h3>Sign In to <strong>SpotiFynder</strong></h3>
              <p class="mb-4">" We match people by their music taste, not by their looks. "</p>
            </div>
            <form action="#" method="post">
              <div class="form-group first">
                <%= form.label :username %>
                <%= form.text_field :username, :class => "form-control" %>
              </div>
              <div class="form-group last mb-4">
                <%= form.label :password %>
                <%= form.password_field :password, :class => "form-control" %>
              </div>
              <%= form.submit "Log In", :class => "btn btn-pill text-white btn-block btn-primary" %>

              <span class="d-block text-center my-4 text-muted"> or sign up with</span>
              <div class="social-login text-center">
                <a href='/auth/spotify' data-method="POST" class="spotify">
                  <span class="iconify" data-icon="bi:spotify"></span>
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_signup_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.hidden_field :spotify_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'signup_form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<!-- Header-->
<%= render 'bg_circles' do %>
      <h1 class="masthead-heading mb-0">One Page Wonder</h1>
      <h2 class="masthead-subheading mb-0">Will Rock Your Socks Off</h2>
      <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Learn More</a>
<% end %>
<!-- Content section 1-->
<section id="scroll">
  <div class="container px-5">
    <div class="row gx-5 align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5"><%= image_tag "01.jpg", :class =>"img-fluid rounded-circle" %></div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">For those about to rock...</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse
            assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae
            adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Content section 2-->
<section>
  <div class="container px-5">
    <div class="row gx-5 align-items-center">
      <div class="col-lg-6">
        <div class="p-5"><img class="img-fluid rounded-circle" src=<%= path_to_image("02.jpg") %> alt="..." /></div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">We salute you!</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse
            assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae
            adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Content section 3-->
<section>
  <div class="container px-5">
    <div class="row gx-5 align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5"><img class="img-fluid rounded-circle" src=<%= path_to_image("03.jpg") %> alt="..." /></div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Let there be rock!</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse
            assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae
            adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/login.html.erb
<%= render 'bg_circles' do %>
    <%= render 'signin_form', user: @user %>
    <%= link_to 'Back', users_path, :class => "btn btn-primary btn-xl rounded-pill mt-5" %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'signup_form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Spotify:</strong>
  <%= @user.spotify_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>